personal/personal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videos/', include('videos.urls')),
]

personal/videos/urls.py
from django.urls import path
from . import views


app_name = 'videos'
urlpatterns = [
    path('', views.index, name='index'),
    path('check_resource/', views.check_resource, name='check_resource'),

]

personal/links/models.py
from django.db import models


class Link(models.Model):
    link = models.URLField('Ссылка', unique=True)
    categories = models.ManyToManyField(
        'tech.Category',
        verbose_name='Категории',
        blank=True,
        related_name='links',
    )
    description = models.CharField('Описание', max_length=200)

    def __str__(self):
        return '{}. {}'.format(self.categories_list, self.description)

    class Meta:
        ordering = ('description', )
        verbose_name = 'Ссылка'
        verbose_name_plural = 'Ссылки'

    @property
    def categories_list(self):
        return ', '.join([category.title for category in self.categories.all()])

personal/tech/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField('Категория', max_length=100, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title', )
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

personal/videos/models.py
from django.db import models


class Video(models.Model):
    link = models.URLField('Ссылка', unique=True)
    categories = models.ManyToManyField(
        'tech.Category',
        verbose_name='Категории',
        blank=True,
        related_name='videos',
    )
    title = models.CharField('Название', max_length=200)
    description = models.CharField('Описание', max_length=200, null=True, blank=True)
    language = models.CharField('Язык', max_length=2, choices=[('ru', 'RU'), ('en', 'EN')], default='RU')
    difficult = models.CharField(
        'Сложность',
        max_length=20,
        choices=[
            ('1', 'начальный уровень'),
            ('2', 'требуется подготовка'),
            ('3', 'для профи')
        ],
        default='1',
    )
    author_github_link = models.URLField('Ссылка на проект автора в GitHub', null=True, blank=True, unique=True)
    my_github_link = models.URLField('Ссылка на мой проект в GitHub', null=True, blank=True, unique=True)

    def __str__(self):
        return '{}. {}'.format(self.categories_str, self.title)

    class Meta:
        ordering = ('title', )
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

    @property
    def categories_str(self):
        return ', '.join([category.title for category in self.categories.all()])

personal/links/views.py
from django.shortcuts import render

# Create your views here.

personal/tech/views.py
from django.shortcuts import render

# Create your views here.

personal/videos/views.py
from collections import defaultdict
from http import HTTPStatus
import requests
from requests.exceptions import ConnectionError
from django.http import JsonResponse
from django.shortcuts import render

from .models import Video
from core.services import check_resource


def index(request):
    videos = Video.objects.all()
    template = 'videos/index.html'
    videos_dict = defaultdict(list)
    for video in videos:
        video_item = {}
        video_item['link'] = video.link
        video_item['link_status'] = video.link
        video_item['title'] = video.title
        video_item['description'] = video.description
        video_item['language'] = video.language
        video_item['difficult'] = video.difficult
        if video.author_github_link:
            video_item['author_github_link'] = video.author_github_link
        if video.my_github_link:
            video_item['my_github_link'] = video.my_github_link
        for category in video.categories.all():
            videos_dict[category.title].append(video_item)
    context = {
        'videos': dict(videos_dict),
    }
    return render(request, template, context)


def check_resource(request):
    link = request.GET.get('link', None)
    print(link)

    try:
        net_response = requests.get(link)
        result = net_response.status_code == HTTPStatus.OK
    except ConnectionError:
        result = False
    # print(net_response.status_code)
    response = {
        'availability': result
    }
    return JsonResponse(response)

personal/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/a670751d49.js" crossorigin="anonymous"></script>
  </head>
  <body>
  {% include 'include/nav.html' %}
  <section class="section">
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </section>
  {% block javascript %}
  {% endblock %}
  </body>
</html>

personal/templates/include/nav.html
<nav class="navbar is-light has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu is-light">
    <div class="navbar-start">
      <a class="navbar-item">
        Стек
      </a>

      <a class="navbar-item">
        Ссылки
      </a>

      <a class="navbar-item">
        Видео
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

personal/templates/videos/index.html
{% extends 'base.html' %}

{% block title %}
Видео
{% endblock %}

{% block content %}
{% for category, video_items in videos.items %}
<section class="section">
  <h1 class="title">{{ category }}</h1>
    {% with name=forloop.counter0 %}
    {% for item in video_items %}
    <div class="block">
        {% if item.link_status %}
        <i class="fas fa-link" id="{{ name }}{{ forloop.counter0}}0"></i>
        <a href="{{ item.link }}" target="_blank" class="resourcelink" rel="{{ name }}{{ forloop.counter0}}0">{{ item.title }}</a> [{{ item.language }}] {{ item.difficult }}
        {% else %}
        <i class="fas fa-link" style="color:red"></i>
        {{ item.title }} [{{ item.language }}] {{ item.difficult }}
        {% endif %}

        {% if item.author_github_link %}
            <a href="{{ item.author_github_link }}" target="_blank" title="Проект на GitHub автора" rel="{{ name }}{{ forloop.counter0}}1" class="resourcelink"><i class="fa fa-github" id="{{ name }}{{ forloop.counter0}}1"></i></a>
        {% endif %}
        {% if item.my_github_link %}
            <a href="{{ item.my_github_link }}" target="_blank" title="Проект на моём GitHub" rel="{{ name }}{{ forloop.counter0}}2" class="resourcelink"><i class="fa fa-github-alt" id="{{ name }}{{ forloop.counter0}}2"></i></a>
        {% endif %}


    </div>
    {% endfor %}
    {% endwith %}
</section>
{% endfor %}
{% endblock %}

{% block javascript %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <script>
      $(document).ready(function () {
          $('.resourcelink').each(function() {
              var target = '#' + $(this).attr('rel');
              var item = $(this);
              $.ajax({
                  data: {"link": $(this).attr('href')},
                  url: "{% url 'videos:check_resource' %}",
                  success: function (response) {
                      if (response.availability == true) {
                          $(target).css('color', 'green');
                      } else {
                          $(target).css('color', 'red');
                          $(item).removeAttr('href').css("cursor","not-allowed");
                          // $(item).remove();
                      }
                  }
              });
          });
      });
  </script>
{% endblock %}